# available directory themes:
# spearmint, peppermint, hemingway, brookmint
theme = 'spearmint'

[general]
title = "Cloud Monitoring Platforms"
logo = ""
iconLogo = "tabler:coffee"

[general.seo]
name = "Cafe Directory"
description = "Find the best nuxt starter kits."
url = "https://nuxtstarters.com"

[directoryData.source]
name = "json"    # default, mock, sheets, json
links = "normal"

[directoryData.tagPages]
title = "{0} Apps"

[directoryData.search]
placeholder = "Search among {0} listings of this directory :)"

[[directoryData.tags]]
key = "apm"
name = "Application Performance"
color = "blue"
emoji = "material-symbols:query-stats"
description = "Application Performance Monitoring."

[[directoryData.tags]]
key = "cloud"
name = "Cloud"
color = "green"
emoji = "material-symbols:cloud"
description = "Cloud infrastructure monitoring."

[[directoryData.tags]]
key = "containers"
name = "Containers"
color = "purple"
emoji = "material-symbols:deployed-code-outline"
description = "Container monitoring and orchestration."

[[directoryData.tags]]
key = "cost"
name = "Cost"
color = "purple"
emoji = "material-symbols:attach-money"
description = "Cost management and optimization."

[[directoryData.tags]]
key = "database"
name = "Databases"
color = "green"
emoji = "material-symbols:database"
description = "Database monitoring and performance."

[[directoryData.tags]]
key = "infrastructure"
name = "Infrastructure"
color = "green"
emoji = "material-symbols:lan"
description = "Infrastructure monitoring."

[[directoryData.tags]]
key = "kubernetes"
name = "Kubernetes"
color = "green"
emoji = "material-symbols:cloud-circle"
description = "Kubernetes monitoring."

[[directoryData.tags]]
key = "monitoring"
name = "General Monitoring"
color = "green"
emoji = "material-symbols:monitoring"
description = "General monitoring."

[[directoryData.tags]]
key = "network"
name = "Network"
color = "green"
emoji = "material-symbols:public"
description = "Network monitoring."

[[directoryData.tags]]
key = "open-source"
name = "Open-Source"
color = "green"
emoji = "material-symbols:code"
description = "Open-source monitoring solutions."

[[directoryData.tags]]
key = "performance"
name = "Performance"
color = "green"
emoji = "material-symbols:speed"
description = "Performance monitoring."

[[directoryData.tags]]
key = "security"
name = "Security"
color = "green"
emoji = "material-symbols:security"
description = "Security monitoring."

[[directoryData.tags]]
key = "server"
name = "Server"
color = "green"
emoji = "material-symbols:dns"
description = "Server monitoring."

[[directoryData.tags]]
key = "uptime"
name = "Uptime Monitoring"
color = "green"
emoji = "material-symbols:timer"
description = "Uptime monitoring and alerting."

[[directoryData.tags]]
key = "website"
name = "Website Monitoring"
color = "green"
emoji = "material-symbols:language"
description = "Website monitoring."

[header.banner]
show = false
text = ""
link = "https://x.com/"
brandText = ""

[header.navbar]
colorModeSelector = true

[[header.navbar.links]]
name = "Blog"
href = "/blog"

[footer]
description = "Cloud monitoring platform directory."

[footer.socials.x]
link = "https://x.com/"

[footer.socials.youtube]
link = "https://www.youtube.com/"

[listings]
pageHeader = 'none' # none, title

[directoryUI]

[directoryUI.search]
showCount = true
icon = "tabler:bow"

[directoryUI.search.tags]
display = "show-all" # options: none,select,show-all
intersection = false

[directoryUI.grid]
list = false
type = "small-card-grid" # options: icon-list, small-card-grid, rectangle-card-grid

[directoryUI.grid.emptyState]
text = "Seems that this entry is missing from the archives."
type = "button"          # options: button, simple, link
icon = "tabler:exclamation-mark"

[directoryUI.grid.card]
image = true

[directoryUI.grid.submit]
show = true
first = false
title = "Submit a template"
description = "Submit a template to show off a good project to other people."
hideable = true

[directoryUI.featured]
showOnAllPages = true
showOnSide = true
icon = "tabler:star"
labelForCard = "Featured ✨"

[ui]

[ui.icons]
dark = "tabler:moon"
light = "tabler:sun"
youtube = "tabler:brand-youtube"
x = "tabler:brand-twitter"
instagram = "tabler:brand-instagram"
facebook = "tabler:brand-facebook"
github = "tabler:brand-github"

[layout]
sidebar = false
emoji = false